### ISSUE TITLE
[wpe-2.22] WebRTC build is broken after d22e12656a29a79232f20cc696645ce15746577e

### ISSUE THREAD

**Issue by emutavchi** [Metrological/WebKitForWayland#734]
The RTCPeerConnection.onicecandidateerror cherry-pick doesn't compile:
```
In file included from DerivedSources/WebCore/JSRTCPeerConnectionIceErrorEvent.h:28:0,
                 from DerivedSources/WebCore/JSDOMWindow.cpp:744,
                 from DerivedSources/WebCore/unified-sources/UnifiedSource20.cpp:7:
/home/imutav200/llama/build-sky-llama-panel/tmp/work/armv7at2hf-neon-rdk-linux-gnueabi/wpe-webkit/2.22.3+gitAUTOINC+b80af163c5-r0/git/Source/WebCore/Modules/mediastream/RTCPeerConnectionIceErrorEvent.h:32:33: fatal error: wtf/text/AtomString.h: No such file or directory
 #include <wtf/text/AtomString.h>
```

**Comment by magomez** [comment]
Arg! you're right, this is totally my fault. I didn't realize I was building without WebRTC when I backported this fix. I'll revert it.

**Comment by magomez** [comment]
I'm trying to fix the build with the commit before reverting it. It should be easy, but building with openwebrtc/libwebrtc to test the fix is being a bit painful.

**Comment by magomez** [comment]
In the end I found that the patch (which comes backported from a newer branch) did depend on features that were not present in 2.22, so it's not possible to make it work without huge changes. I pushed 3cebb77d6f6e3477770aa78819cd074f337f6977 that reverts the problematic commit.

**Comment by emutavchi** [comment]
Thanks
