### ISSUE TITLE
[wpe-2.42] JavaScriptCore build is broken after a66301835162306f74856880da13412f5fbe0381

### ISSUE THREAD

**Issue by enocknt** [Metrological/WebKitForWayland#1289]
After the latest [merge commit](https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/a66301835162306f74856880da13412f5fbe0381) applied to [wpe-2.42](https://github.com/WebPlatformForEmbedded/WPEWebKit/commits/wpe-2.42) branch, the JavaScriptCore build was broken.

```shell
 .../webkit/Source/JavaScriptCore/llint/LowLevelInterpreter.cpp:339:21:
    error: use of undeclared identifier 't6'

        UNUSED_VARIABLE(t6);
                        ^
 .../webkit/Source/JavaScriptCore/llint/LowLevelInterpreter.cpp:340:21:
    error: use of undeclared identifier 't7'

        UNUSED_VARIABLE(t7);
                        ^
    2 errors generated.
```

The issue can be seen in [LowLevelInterpreter.cpp](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/a66301835162306f74856880da13412f5fbe0381/Source/JavaScriptCore/llint/LowLevelInterpreter.cpp) on lines [338](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/a66301835162306f74856880da13412f5fbe0381/Source/JavaScriptCore/llint/LowLevelInterpreter.cpp#L338) and [339](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/a66301835162306f74856880da13412f5fbe0381/Source/JavaScriptCore/llint/LowLevelInterpreter.cpp#L339).

https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/a66301835162306f74856880da13412f5fbe0381/Source/JavaScriptCore/llint/LowLevelInterpreter.cpp#L338-L339

This occurs due to the variables `t6` and `t7` not being defined on line [326](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/a66301835162306f74856880da13412f5fbe0381/Source/JavaScriptCore/llint/LowLevelInterpreter.cpp#L326).

https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/a66301835162306f74856880da13412f5fbe0381/Source/JavaScriptCore/llint/LowLevelInterpreter.cpp#L326

This issue is resolved at https://github.com/WebKit/WebKit/commit/3d5373575695b293b8559155431d0079a6153aff.

**Comment by magomez** [comment]
I've just pushed the fix for this to the wpe-2.42 branch. Thanks the detailed report!
